### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by sirius-aerostar** [lucadellalib/bayesian-deep-rul#1]
Dataset: CMAPSS/FD001
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    MODEL = getattr(module, cls)(input_size).to(DEVICE)
  File "models/frequentist_dense3.py", line 23, in __init__
    nn.Linear(input_size[0] * input_size[1] * input_size[2], 100, bias=False),
  File "/home/test/anaconda2/envs/bayesian-deep-rul/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 77, in __init__
    self.reset_parameters()
  File "/home/test/anaconda2/envs/bayesian-deep-rul/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 80, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/test/anaconda2/envs/bayesian-deep-rul/lib/python3.6/site-packages/torch/nn/init.py", line 316, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero

**Comment by lucadellalib** [comment]
Hi @sirius-aerostar,
you first need to download and preprocess the raw data as described in *datasets/CMAPSS/README.md*. Open a terminal in *datasets/CMAPSS* and run:

`sh download_cmapss.sh`

`python3 cmapss_preprocessing.py`

**Comment by sirius-aerostar** [comment]
It works. Thank you.

**Comment by lvyilan23** [comment]
> Hi @sirius-aerostar,
> you first need to download and preprocess the raw data as described in datasets/CMAPSS/README.md. Open a terminal in datasets/CMAPSS and run:
> sh download_cmapss.sh
> python3 cmapss_preprocessing.py

Hi, I meet the similar question in my own data and code. Can you explain to me why this happens? Will it work if I use the cmapss_preprocessing.py to process my data?

**Comment by lucadellalib** [comment]
Hi @lvyilan23,
*cmapss_preprocessing.py* preprocesses the raw data that you download through *download.sh* and saves them into *.txt* files in the folder *data*. Simply, if you don't run *cmapss_preprocessing.py*, the folder *data* is empty and the info required to initialize the model  (e.g. number of features) cannot be retrieved (they are set to 0 by default), causing that error (a value that should not be 0 is 0 because there were no data from which to read it). It works if you first run *cmapss_preprocessing.py*.
